{{- $pkg := "podinfo" }}
{{- $component := "sandbox" }}
{{- $fluxSettings := merge (get .Values $pkg).flux .Values.flux -}}
{{- if (get .Values $pkg).enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ $pkg }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $pkg }}
    app.kubernetes.io/component: {{ $component | quote }}
    {{- include "commonLabels" . | nindent 4}}
spec:
  targetNamespace: {{ $pkg }}
  chart:
    spec:
      chart: {{ (get .Values $pkg).git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: {{ .Values.gitRepoName }}
        namespace: {{ .Release.Namespace }}

  {{- toYaml $fluxSettings | nindent 2 }}

  {{- if (get .Values $pkg).postRenderers }}
  postRenderers:
  {{ toYaml (get .Values $pkg).postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-{{ $pkg }}-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-{{ $pkg }}-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-{{ $pkg }}-values
      kind: Secret
      valuesKey: "overlays"

  {{- if or .Values.bb_gatekeeper.enabled .Values.bb_istio.enabled .Values.bb_monitoring.enabled }}
  dependsOn:
    {{- if .Values.bb_gatekeeper.enabled }}
    - name: gatekeeper
      namespace: bigbang
    {{- end }}
    {{- if .Values.bb_istio.enabled }}
    - name: istio
      namespace: bigbang
    {{- end }}
    {{- if .Values.bb_monitoring.enabled }}
    - name: monitoring
      namespace: bigbang
    {{- end }}
  {{- end }}
{{- end }}
